// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiCanon.Data;

#nullable disable

namespace WebApiCanon.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiCanon.Features.Machines.MachineItems", b =>
                {
                    b.Property<long>("MachineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MachineId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MachineId");

                    b.ToTable("MachineItems");
                });

            modelBuilder.Entity("WebApiCanon.Features.Productions.DailyProduction", b =>
                {
                    b.Property<long>("DailyProductionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DailyProductionId"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("DefectUnits")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("MachineId")
                        .HasColumnType("bigint");

                    b.Property<int>("OkUnits")
                        .HasColumnType("int");

                    b.Property<int>("TargetUnits")
                        .HasColumnType("int");

                    b.HasKey("DailyProductionId");

                    b.HasIndex("MachineId");

                    b.ToTable("DailyProductions");
                });

            modelBuilder.Entity("WebApiCanon.Features.Productions.DailyProduction", b =>
                {
                    b.HasOne("WebApiCanon.Features.Machines.MachineItems", "Machine")
                        .WithMany("DailyProductions")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("WebApiCanon.Features.Machines.MachineItems", b =>
                {
                    b.Navigation("DailyProductions");
                });
#pragma warning restore 612, 618
        }
    }
}
